RINGCENTRAL_SERVER: https://platform.ringcentral.com
RINGCENTRAL_CHATBOT_DATABASE_CONNECTION_URI: postgresql://user@pass@xxxxx.us-east-1.rds.amazonaws.com/prod-db
RINGCENTRAL_CHATBOT_CLIENT_ID:
RINGCENTRAL_CHATBOT_CLIENT_SECRET:
RINGCENTRAL_CHATBOT_SERVER: https://xxxxxxx.execute-api.us-east-1.amazonaws.com/prod

RINGCENTRAL_APP_CLIENT_ID:
RINGCENTRAL_APP_CLIENT_SECRET:

AWS_LEX_BOT_NAME: GlipBot
AWS_LEX_BOT_ALIAS: GlipBot

RINGCENTRAL_SERVICE_WEB_SERVER: https://service.ringcentral.com

RINGCENTRAL_CHATBOT_ADMIN_USERNAME: admin
RINGCENTRAL_CHATBOT_ADMIN_PASSWORD: admin
