service: glip-rc-assistant-chatbot
configValidationMode: error

provider:
  lambdaHashingVersion: 20201221
  stage: prod
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256
  timeout: 30 # maximum value allowed by api gateway
  environment: ${file(./.env.yml)}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lex:PostText
          Resource: "*"
package:
  patterns:
    - '!./**'
    - 'dist/**'
    - 'node_modules/**'
  excludeDevDependencies: true
functions:
  app:
    handler: dist/lambda.app
    timeout: 300 # 5 minutes
    events:
      - http: 'GET /admin/dump-database'
      - http: 'GET /admin/list-subscriptions'
  proxy:
    handler: dist/lambda.proxy
    events:
      - http: 'ANY /{proxy+}'
  maintain:
    handler: dist/lambda.maintain
    events:
      - schedule: rate(1 day)
